from app.models.entities import UserRole

ALL_PERMISSIONS = {
    "product:read",
    "product:write",
    "inventory:read",
    "inventory:adjust",
    "sale:create",
    "sale:refund",
    "customer:read",
    "customer:write",
    "order:read",
    "order:write",
    "order:confirm",
    "order:cancel",
    "shipment:create",
    "return:create",
    "purchase:write",
    "report:read",
    "audit:read",
    "staff:manage",
    "settings:manage",
}

ROLE_PERMISSIONS: dict[UserRole, set[str]] = {
    UserRole.OWNER: ALL_PERMISSIONS,
    UserRole.MANAGER: ALL_PERMISSIONS - {"staff:manage"},
    UserRole.CASHIER: {"product:read", "inventory:read", "sale:create", "customer:read"},
    UserRole.SUPPORT: {
        "product:read",
        "inventory:read",
        "customer:read",
        "customer:write",
        "order:read",
        "order:write",
        "order:confirm",
        "order:cancel",
        "shipment:create",
        "return:create",
    },
    UserRole.WAREHOUSE: {
        "product:read",
        "inventory:read",
        "inventory:adjust",
        "order:read",
        "shipment:create",
        "return:create",
        "purchase:write",
    },
}
